### ISSUE TITLE
Refactor defaults variables that involve urls and file names

### ISSUE THREAD

**Issue by dyegoe** [dyegoe/ansible-k8s-cluster#29]
Taking openebs example, I think it is easier the approach to have manifests and/or other variables that involves urls and files as destinations to be refactored to be more flexible and easy to use.

```yaml
kube_dashboard_manifests:
  - url: https://raw.githubusercontent.com/kubernetes/dashboard/{{ kube_dashboard_version }}/aio/deploy/recommended.yaml
    filename: recommended.yaml
```
