### ISSUE TITLE
Include wait to all kubernetes related tasks

### ISSUE THREAD

**Issue by dyegoe** [dyegoe/ansible-k8s-cluster#30]
As en example

```yaml
- name: Download manifest
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ openebs_temp_dir.path }}/{{ item.filename }}"
    mode: "0555"
  loop: "{{ openebs_manifests }}"
  loop_control:
    label: "{{ item.filename }}"

- name: Apply manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ openebs_temp_dir.path }}/{{ item.filename }}"
    wait: true ## <<<<<< add this to the kubernetes tasks
  loop: "{{ openebs_manifests }}"
  loop_control:
    label: "{{ item.filename }}"
```
